### ISSUE TITLE
Remove external dependency on requests

### ISSUE THREAD

**Issue by marekkowalczyk** [winsbe01/booki#1]
```
$ booki
Traceback (most recent call last):
  File "/usr/local/bin/booki", line 10, in <module>
    import requests
ImportError: No module named requests
```

**Comment by winsbe01** [comment]
Thanks for the bug report!

Short answer: `pip install requests` will bring that module into the global namespace, and should resolve this error. Let me know if it doesn't, or if you're going to hold out for the fix below.

Long(er) answer: I may refactor this to not depend on external modules, for this explicit purpose (I forgot `requests` was not a part of the standard library, which was why it slipped through), and/or figure out how to package Python programs (with dependencies) neatly.

**Comment by winsbe01** [comment]
Fixed with [37b8bdd](https://github.com/winsbe01/booki/commit/37b8bdd152dd2f377d483113e92a0d678a61139d)

**Comment by marekkowalczyk** [comment]
Still getting an analogous error:

```
$ booki
Traceback (most recent call last):
  File "/usr/local/bin/booki", line 10, in <module>
    import urllib.request
ImportError: No module named request
```

**Comment by winsbe01** [comment]
Hi Marek -- my guess is your `python` interpreter was defaulting to Python 2. I just pushed a fix so it will explicitly call Python 3. Let me know if that works for you!

**Comment by marekkowalczyk** [comment]
Launches fine :) thanks.
